crowdsecurity/crowdsec-docs

docs/v1.X/docs/user_guide/data_sources/journalctl.md
Fixing a small mistake in a configuration example.
This causes crowdsec to fail with the following error message:
> crowdsec init: Error while loading acquisition config : while loading acquisition configuration: data source type is empty ('source') in /etc/crowdsec/acquis.yaml
=> Fix journalctl datasource example

crowdsec-docs/docs/bouncers/nginx.mdx
I noticed that the nginx bouncer recently needs lua-cjson to be installed additionally on Debian 11 or nginx will refuse to start with the crowdsec config in place.
=> add lua-cjson to requirements

crowdsec-docs/docs/bouncers/blocklist-mirror.mdx
Merge this after we have something at https://hub.docker.com/r/crowdsecurity/blocklist-mirror
=> Add link to docker hub docs for blocklist mirror

crowdsec-docs/docs/bouncers/firewall.mdx
ispet seemed wrong in the context of the document. I assume that the command ipset is meant and changed the two occurrences.
=> fixed typo ipset in the firewall bouncer doc

crowdsec-docs/versioned_docs/version-v1.4.0/notification_plugins/intro.md
For Oracle Linux Server 8.x, the `config_paths.plugin_dir` defaults to `/usr/lib64/crowdsec/plugins/` instead of `/var/lib/crowdsec/plugins/`.
=> Added note to verify the path before registration.

crowdsec-docs/docs/configuration/crowdsec_configuration.md
Based on the underlaying [lumberjack logger's docs](https://github.com/natefinch/lumberjack) add details on the configuration of log rotation.
- Add unit
- Add defaults (based on [apiserver.go](https://github.com/crowdsecurity/crowdsec/blob/16a3be49e26d0ba9c378461f5bf335224b38abbe/pkg/apiserver/apiserver.go#L146-L180))
=> Add log rotation details

crowdsec-docs/docs/observability/prometheus.md, crowdsec-docs/versioned_docs/version-v1.5.0/observability/prometheus.md
Added some help text to let the user know where they can edit the listen_addr to allow an external Prometheus to scrape metrics.
If the added text would be better placed somewhere else please provide feedback.
=> Update prometheus.md to include help text on scraping

crowdsec-docs/docs/local_api/intro.md
for this usage I guess machine is preferred over agent.
=> consistent naming for machine and agent

crowdsec-docs/versioned_docs/version-v1.0/whitelist/create.md, crowdsec-docs/versioned_docs/version-v1.1/whitelist/create.md, crowdsec-docs/versioned_docs/version-v1.2.2/whitelist/create.md, crowdsec-docs/versioned_docs/version-v1.2/whitelist/create.md, crowdsec-docs/versioned_docs/version-v1.3.0/whitelist/create.md, crowdsec-docs/versioned_docs/version-v1.3.4/whitelist/create.md, crowdsec-docs/versioned_docs/version-v1.4.0/whitelist/create.md, crowdsec-docs/versioned_docs/version-v1.5.0/whitelist/create.md
Correct path for postoverflow whitelist:
`/etc/crowdsec/postoverflows/s01-whitelists/...` -> `/etc/crowdsec/postoverflows/s01-whitelist/...`
=> Fix typo in docs/whitelist/create (fixes #441)

crowdsec-docs/src/components/tableRender.js
There was an error present _at least_ on the following page: https://docs.crowdsec.net/docs/next/cti_api/taxonomy/classifications/
Here's how it currently looks:
This is caused by issues in the theming part.
This PR fixes the issue by properly building the theme.
=> fix: remove runtime error caused by theme issue

crowdsec-docs/docs/local_api/database.md
Postgres 15 does not allow creation of tables in `public` (default)  schema without  super-user access rights. `crowdsec` has to be made the owner of the public schema first. See https://stackoverflow.com/questions/74110708/postgres-15-permission-denied-for-schema-public. 
Public schemas are also in version 14 and 13, but the required access rights have been changed in 15.0.
=> Update postgresql instructions for Postgresql 15

crowdsec-docs/docs/getting_started/getting_started.md, crowdsec-docs/docs/getting_started/getting_started_on_windows.md, crowdsec-docs/docs/getting_started/install.mdx, crowdsec-docs/docs/getting_started/install_freebsd.md, crowdsec-docs/docs/getting_started/install_opnsense.md, crowdsec-docs/docs/getting_started/install_pfsense.md
whenever we link to console for enrollment purposes we should link to security-engines page with this query parameter as web team have implemented a nice QOL
=> [Console] links to shortcut enrollment screen

crowdsec-docs/unversioned/bouncers/openresty.mdx
As per the title renaming the Appsec config file title from `/etc/crowdsec/bouncers/crowdsec-nginx-bouncer.conf` into `/etc/crowdsec/bouncers/crowdsec-openresty-bouncer.conf`
=> Fixing Openresty Appsec Title

crowdsec-docs/unversioned/bouncers/cloudflare-workers.mdx
Added a section in doc to guide user through using the Bouncer ont he Cloudflare free plan despite that plan's limitations
Additionnal section preview in Docusaurus : [Appendix: Test with Cloudflare free plan](https://pr-539.d1to60jd2gb6y6.amplifyapp.com/u/bouncers/cloudflare-workers#appendix-test-with-cloudflare-free-plan)
=> add precisions about testing the CF worker bouncer on CF free plan

crowdsec-docs/docs/configuration/crowdsec_configuration.md, crowdsec-docs/versioned_docs/version-v1.5.0/configuration/crowdsec_configuration.md
The documentation states that the `use_forwarded_for_headers` directive has the type `string` on one instance, but it's a `bool`
=> Fix wrong type in crowdsec_configuration docs for use_forwarded_for_headers

crowdsec-docs/docs/data_sources/journald.md
It is possible to get more informations easily rather that specify for each services
https://www.man7.org/linux/man-pages/man7/systemd.journal-fields.7.html
=> Set a more generic way to acquire all event from journald

crowdsec-docs/docs/configuration/crowdsec_configuration.md, crowdsec-docs/versioned_docs/version-v1.3.4/configuration/crowdsec_configuration.md, crowdsec-docs/versioned_docs/version-v1.4.0/configuration/crowdsec_configuration.md, crowdsec-docs/versioned_docs/version-v1.5.0/configuration/crowdsec_configuration.md, crowdsec-docs/versioned_docs/version-v1.6.0/configuration/crowdsec_configuration.md
fix #581 
Instead of having the yaml coded into the page link to the github repo for that version
=> fix: config file links

crowdsec-docs/docs/notification_plugins/http.md
Add `unix_socket` key to `http_default` since the documentation does not really keep all parameters in an order.
=> enhance: add unix socket comment to http_default

crowdsec-docs/docs/notification_plugins/elasticsearch.md, crowdsec-docs/docs/notification_plugins/email.md, crowdsec-docs/docs/notification_plugins/file.md, crowdsec-docs/docs/notification_plugins/gotify.md, crowdsec-docs/docs/notification_plugins/helpers.md, crowdsec-docs/docs/notification_plugins/http.md, crowdsec-docs/docs/notification_plugins/intro.md, crowdsec-docs/docs/notification_plugins/sentinel.md, crowdsec-docs/docs/notification_plugins/slack.md, crowdsec-docs/docs/notification_plugins/splunk.md, crowdsec-docs/docs/notification_plugins/teams.md, crowdsec-docs/docs/notification_plugins/telegram.md
=> enhance: add new testing section and refactor the structure

crowdsec-docs/docs/appsec/benchmark.md, crowdsec-docs/docs/appsec/configuration.md, crowdsec-docs/docs/appsec/create_rules.md, crowdsec-docs/docs/appsec/hooks.md, crowdsec-docs/docs/appsec/installation.md, crowdsec-docs/docs/appsec/intro.md, crowdsec-docs/docs/appsec/protocol.md, crowdsec-docs/docs/appsec/quickstart.md, crowdsec-docs/sidebars.js, crowdsec-docs/yarn.lock
Changes in titles and sidebar only for this section : https://pr-633.d1to60jd2gb6y6.amplifyapp.com/docs/next/appsec/intro
=> Mention WAF in appsec doc ahead of WAF articles

crowdsec-docs/docs/whitelist/expr_based_whitelist.md, crowdsec-docs/docs/whitelist/format.md, crowdsec-docs/docs/whitelist/fqdn_based_whitelist.md, crowdsec-docs/docs/whitelist/ip_based_whitelist.md, crowdsec-docs/docs/whitelist/postoverflow_based_whitelist.md, crowdsec-docs/versioned_docs/version-v1.3.4/whitelist/create.md, crowdsec-docs/versioned_docs/version-v1.4.0/whitelist/create.md, crowdsec-docs/versioned_docs/version-v1.5.0/whitelist/create.md, crowdsec-docs/versioned_docs/version-v1.6.0/whitelist/expr_based_whitelist.md, crowdsec-docs/versioned_docs/version-v1.6.0/whitelist/ip_based_whitelist.md
Some users will just copy and paste, not to know they need to change the name key, so change this to be something other than the official one and add a comment on the latest docs to say "Must be unique" to try inform them to change it.
=> enhance: Whitelist change name key to not conflict with our official one

crowdsec-docs/unversioned/cti_api/taxonomy/cti_fields.md, crowdsec-docs/unversioned/cti_api/taxonomy/scores.md
Adjusted the cti docs to reflect the message of the new scoring system. Also includes some minor Frenglish corrections and phrasing changes to make the content more digestible.
=> Improve cti docs

crowdsec-docs/docs/getting_started/install.mdx, crowdsec-docs/unversioned/getting_started/installation/linux.mdx
add documentation for OpenSUSE
=> add documentation for opensuse

crowdsec-docs/docs/local_api/notification_plugins/intro.md
ref: https://github.com/crowdsecurity/crowdsec/issues/2923
=> enhancement: Add information about environment variables in the notificiations

crowdsec-docs/unversioned/getting_started/installation/kubernetes.mdx
Updating the cited `apiVersion` of the Middleware manifest in the Kubernetes getting started guide to match current traefik standards.
I can also update the guide to use mutual TLS for bouncer authentication if desired, but wasn't sure if that was an intentional choice for the getting started guide.
=> fix: update traefik middleware apiVersion

crowdsec-docs/docs/configuration/crowdsec_configuration.md
=> enhance: add ssl opts for db connections

crowdsec-docs/components.json, crowdsec-docs/package-lock.json, crowdsec-docs/package.json, crowdsec-docs/src/components/RemediationSupportBadges.tsx, crowdsec-docs/src/components/RemediationSupportTable.tsx, crowdsec-docs/src/ui/tooltip.tsx, crowdsec-docs/src/utils/index.ts, crowdsec-docs/tailwind.config.js, crowdsec-docs/tsconfig.json, crowdsec-docs/unversioned/bouncers/aws-waf.mdx, crowdsec-docs/unversioned/bouncers/blocklist-mirror.mdx, crowdsec-docs/unversioned/bouncers/cloudflare-workers.mdx, crowdsec-docs/unversioned/bouncers/cloudflare.mdx, crowdsec-docs/unversioned/bouncers/custom.mdx, crowdsec-docs/unversioned/bouncers/fastly.mdx, crowdsec-docs/unversioned/bouncers/firewall.mdx, crowdsec-docs/unversioned/bouncers/haproxy.mdx, crowdsec-docs/unversioned/bouncers/ingress-nginx.mdx, crowdsec-docs/unversioned/bouncers/intro.md, crowdsec-docs/unversioned/bouncers/magento.mdx, crowdsec-docs/unversioned/bouncers/misp-feed-generator.mdx, crowdsec-docs/unversioned/bouncers/nginx.mdx, crowdsec-docs/unversioned/bouncers/openresty.mdx, crowdsec-docs/unversioned/bouncers/php-lib.mdx, crowdsec-docs/unversioned/bouncers/php.mdx, crowdsec-docs/unversioned/bouncers/windows-firewall.mdx, crowdsec-docs/unversioned/bouncers/wordpress.mdx
To help user see from a glance what feature the remediation supports
=> enhance: add remediation supported features bubble

crowdsec-docs/docs/appsec/quickstart/traefik.mdx
I have followed the documentation, on how to set up WAF with CrowdSec and Traefik. It didn't work, so I took a closer look into the plugin documentation and found this.
Since the default for Enabled is false, Enabled has to be set to true
I want to share this small fix with the community.
=> WAF: Update traefik plugin configuration

crowdsec-docs/unversioned/troubleshooting/intro.md
Without explicitly setting `NO_PROXY=127.0.0.1,localhost,0.0.0.0`, LAPI will throw an error:
> time="2025-04-27T17:41:38+03:00" level=fatal msg="crowdsec init: while initializing LAPIClient: authenticate watcher (crowdsec): Post \"http://0.0.0.0:8080/v1/watchers/login\": performing jwt auth: socks connect tcp 172.24.8.2:1080->0.0.0.0:8080: unknown error connection refused"
=> Instruct to set NO_PROXY to avoid LAPI errors

crowdsec-docs/unversioned/console/decisions/decisions_management.md
We'll have to move or regroup this somewhere in the future. might evolve too with 1.6.9 release
Info on top of that page: https://pr-776.d1to60jd2gb6y6.amplifyapp.com/u/console/decisions/decisions_management
=> Inform that console management must be active for decision management

crowdsec-docs/docs/log_processor/data_sources/kafka.md
Hi!
Following the update to the Kafka datasource in this PR: https://github.com/crowdsecurity/crowdsec/pull/3621/files, I'm contributing to the documentation to reflect the new configuration options.
Since the implementation uses [kafka-go](https://github.com/segmentio/kafka-go), I thought it might be helpful to include the [default values](https://github.com/segmentio/kafka-go/blob/main/reader.go#L629) from the library so users know what happens when they don't explicitly set a parameter.
I haven’t seen other datasources documenting defaults, so I’m not 100% sure about the preferred formatting for this kind of info. Happy to adjust based on your feedback :)
=> update kafka datasource documentation for new batch parameters

crowdsec-docs/docs/appsec/quickstart/nginxopenresty.mdx, crowdsec-docs/docs/appsec/quickstart/traefik.mdx
The goal is to provide information without making the user switch pages, if we linked to the actual pages they may get lost.
=> enhance: Concepts page no longer has information use tooltips instead

crowdsec-docs/unversioned/bouncers/haproxy_spoa.mdx
take tko's feedback into account
=> take tko's feedback into account

crowdsec-docs/src/components/console-promo.tsx, crowdsec-docs/src/css/custom.css
To fix images on main page being small by the wide .container img selector.
Also fixed the console-promo from opening a new page when the link is internal.
=> enhance: fix img css and button on promos

crowdsec-docs/docs/log_processor/whitelist/ip_based_whitelist.md, crowdsec-docs/docs/log_processor/whitelist/postoverflow_based_whitelist.md, crowdsec-docs/versioned_docs/version-v1.6/log_processor/whitelist/ip_based_whitelist.md, crowdsec-docs/versioned_docs/version-v1.6/log_processor/whitelist/postoverflow_based_whitelist.md, crowdsec-docs/versioned_docs/version-v1.7/log_processor/whitelist/ip_based_whitelist.md, crowdsec-docs/versioned_docs/version-v1.7/log_processor/whitelist/postoverflow_based_whitelist.md
https://github.com/crowdsecurity/crowdsec/issues/3845
=> enhance: make example clearer in whitelist

crowdsec-docs/sidebarsUnversioned.ts, crowdsec-docs/unversioned/console/remediation_sync.mdx
Created page:  https://pr-903.d1to60jd2gb6y6.amplifyapp.com/u/console/remediation_sync
=> remediation sync page v0.1

crowdsec-docs/docs/getting_started/install_drupal_plugin.mdx, crowdsec-docs/docs/getting_started/install_php_softagent.md, crowdsec-docs/docs/getting_started/sdk_intro.mdx, crowdsec-docs/sidebars.ts
[New page HERE](https://pr-902.d1to60jd2gb6y6.amplifyapp.com/docs/next/getting_started/install_drupal_plugin)
=> Adding Drupal plugin page in SDK section

crowdsec-docs/unversioned/bouncers/fastly.mdx
:warning: Merge only after release 0.4.0 of the bouncer (https://github.com/crowdsecurity/cs-fastly-bouncer/pull/17)
=> feat(fastly bouncer): Mention -r option
