- docs/v1.X/docs/getting_started/installation.md
document required resources for running crowdsec / metabase
> fix #4 - document required resources

- docs/v1.X/docs/getting_started/installation.md
- fix #8
- fix #9
- update doc for FreeBSD
> Fixes for doc

- docs/v1.X/docs/cscli/cscli.md
- docs/v1.X/docs/cscli/cscli_completion.md
- docs/v1.X/docs/cscli/cscli_console.md
- docs/v1.X/docs/cscli/cscli_console_enroll.md
- docs/v1.X/docs/getting_started/installation.md
- docs/v1.X/docs/observability/dashboard.md
- switch repositories to packagecloud.io
- add RPM packages doc
> doc update : packagecloud + RPM

- docs/v1.X/docs/write_configurations/requirements.md
Tested our `crowdsec` locally by checking out the `master` branch but found out the steps to set it locally using local IDE is not straightfoward. Thought of creating a PR with the steps to helped other developers who are interested to contribute code.
> Update contribution docs to provide local development setup

- crowdsec-docs/docs/notification_plugins/intro.md
- crowdsec-docs/docs/notification_plugins/slack.md
- crowdsec-docs/docs/notification_plugins/splunk.md
- crowdsec-docs/docs/notification_plugins/writing_your_own_plugin.md
Finish the writing your own plugin in go guide. 
Add links to various object definitions.
> Add more doc for plugin

- crowdsec-docs/docs/user_guides/hub_management.md
- crowdsec-docs/docusaurus.config.js
- crowdsec-docs/package-lock.json
- crowdsec-docs/package.json
- crowdsec-docs/versioned_docs/version-v1.1/user_guides/hub_management.md
:warning: It looks like we need to deploy this to production before algolia will actually scrape dour doc, so the search will be broken for ~24h after we merge this.
> Add algolia DocSearch

- crowdsec-docs/docs/configuration/crowdsec_configuration.md
- crowdsec-docs/docs/notification_plugins/intro.md
Documents addtional config introduced by https://github.com/crowdsecurity/crowdsec/pull/944
> Document plugin process owner

- crowdsec-docs/docs/configuration/network_management.md
- crowdsec-docs/versioned_docs/version-v1.2/configuration/network_management.md
> fix hub uri

- crowdsec-docs/versioned_docs/version-v1.0/faq.md
> debian bug doc

- crowdsec-docs/docs/notification_plugins/writing_your_own_plugin.md
Prevents https://discourse.crowdsec.net/t/writing-plugin-in-go-errors/372
> Fix import path in plugin docs

- crowdsec-docs/docs/cscli/cscli_bouncers_add.md
- crowdsec-docs/docs/cscli/cscli_config_show.md
- crowdsec-docs/docs/cscli/cscli_explain.md
- crowdsec-docs/docs/user_guides/cscli_explain.md
- cscli explain v2
- minor updates for `cscli config show` and `cscli bouncers add`
> minor updates for new release

- crowdsec-docs/docs/notification_plugins/email.md
- crowdsec-docs/docs/notification_plugins/writing_your_own_plugin.md
- crowdsec-docs/sidebars.js
Documents https://github.com/crowdsecurity/crowdsec/pull/1013
> Add docs for email plugin.

- crowdsec-docs/sidebars.js
- crowdsec-docs/versioned_sidebars/version-v1.2.2-sidebars.json
> include cscli decisions import doc

- crowdsec-docs/docs/data_sources/cloudwatch.md
- crowdsec-docs/docs/data_sources/introduction.md
- crowdsec-docs/docs/data_sources/kinesis.md
- crowdsec-docs/sidebars.js
Merge when https://github.com/crowdsecurity/crowdsec/pull/1147 is merged.
> add kinesis doc

- crowdsec-docs/versioned_docs/version-v1.3.0/concepts.md
> fixed grammar

- crowdsec-docs/versioned_docs/version-v1.3.0/notification_plugins/email.md
modify document relative to PR https://github.com/crowdsecurity/crowdsec/pull/1297
> email notification plugin: add sender_name in example

- crowdsec-docs/docs/getting_started/getting_started_on_windows.md
Text updated after making experience with the installation process.
> Text updated and grammar updated.

- crowdsec-docs/docs/profiles/format.md
cf. https://github.com/crowdsecurity/crowdsec/pull/1326
> document supported duration

- crowdsec-docs/docs/configuration/crowdsec_configuration.md
Documents https://github.com/crowdsecurity/crowdsec/pull/1352
> Document trusted_ips

- crowdsec-docs/docs/observability/dashboard.md
Fixes https://github.com/crowdsecurity/crowdsec/issues/1292#issuecomment-1054287515
> Complete podman tip for metabase

- crowdsec-docs/docs/notification_plugins/intro.md
Fix https://github.com/crowdsecurity/crowdsec-docs/issues/185
> Fix formatting in plugin docs; Clarify plugin level

- crowdsec-docs/versioned_docs/version-v1.3.0/parsers/create.md
Renamed `He specify that` into `We specify that`
> Updated Spello

- crowdsec-docs/docs/troubleshooting.md
> add more stuff to troubleshooting

- crowdsec-docs/docs/bouncers/blocklist-mirror.mdx
- crowdsec-docs/sidebars.js
Merge after https://github.com/crowdsecurity/cs-blocklist-mirror/pull/8
> Add docs for cs-blocklist-mirror

- crowdsec-docs/docs/parsers/create.md
- crowdsec-docs/versioned_docs/version-v1.2.2/parsers/create.md
- crowdsec-docs/versioned_docs/version-v1.3.0/parsers/create.md
> cscli hubtest doc fix

- crowdsec-docs/docs/bouncers/cloudflare.mdx
Documents https://github.com/crowdsecurity/cs-cloudflare-bouncer/pull/84 and https://github.com/crowdsecurity/cs-cloudflare-bouncer/
> Update cf docs

- crowdsec-docs/docs/cscli/cscli_explain.md
> cscli stdin example

- crowdsec-docs/docs/configuration/crowdsec_configuration.md
- crowdsec-docs/docs/profiles/intro.md
Document for https://github.com/crowdsecurity/crowdsec/pull/1497
> document `.yaml.local`

- crowdsec-docs/docs/expr/helpers.md
- crowdsec-docs/docs/profiles/format.md
To merge when after merge this:  https://github.com/crowdsecurity/crowdsec/pull/1556
> expr: update helpers doc

- crowdsec-docs/docs/notification_plugins/email.md
fixes email notification plugin doc for crowdsec from the version 1.4.2
> fixes email notification plugin doc

- crowdsec-docs/versioned_docs/version-v1.4.0/configuration/crowdsec_configuration.md
I think that you can clarify from which version pid_dir is not supported.
> Updating information about pid _dir

- crowdsec-docs/docs/notification_plugins/intro.md
add some doc for notifications plugins debugging
> add some doc for notifications plugins

- crowdsec-docs/docs/configuration/crowdsec_configuration.md
> Document use_wal for SQLite

- crowdsec-docs/docs/configuration/crowdsec_configuration.md
To merge when [this PR](https://github.com/crowdsecurity/crowdsec/pull/1730) is merged
> Add documentation to enable agent/lapi via configuration

- crowdsec-docs/docs/notification_plugins/intro.md
To merge when [this PR](https://github.com/crowdsecurity/crowdsec/pull/1727) will be merged.
> Add documentation about using environment variable in plugins conf

- crowdsec-docs/docs/data_sources/kafka.md
- crowdsec-docs/sidebars.js
Add kafka datasource documentation.
> add kafka datasource doc

- crowdsec-docs/docs/getting_started/versions_matrix.md
- crowdsec-docs/sidebars.js
> matrix version

- crowdsec-docs/docs/data_sources/introduction.md
Let this be the last of this 😆
> Fix windows link

- crowdsec-docs/docs/faq.md
... because I don't know where else?
fix #333
> explain tainted and custom in FAQ 

- crowdsec-docs/docs/getting_started/crowdsec_tour.md
As discussed with @buixor adding the workshop video to the tour page.
> Embed workshop video into crowdsec tour page

- crowdsec-docs/versioned_docs/version-v1.4.0/configuration/crowdsec_configuration.md
This PR adds some clarifications on how to configure the builtin Prometheus exporter.
> Prometheus exporter interface clarifications

- crowdsec-docs/docs/bouncers/windows-firewall.mdx
Just some small edits, but worth changing.
> Windows Firewall Bouncer: Minor changes, such as capitalization and grammar

- crowdsec-docs/docs/parsers/enricher.md
- crowdsec-docs/docs/parsers/format.md
- crowdsec-docs/docs/scenarios/format.md
Improve documentation of parsers, enrichers and scenario a bit.
> Improve documentation of parsers, enrichers and scenario a bit.

- crowdsec-docs/docs/expr/helpers.md
- crowdsec-docs/docs/parsers/format.md
:warning: do not merge before 1.5 :warning: 
- Document stash helpers &  mechanism
- Document `Match` helper
- Document `isIPV4` and `isIP`
- Document the `.Time.Hour()` `.Time.Weekday()` tricks
- Reorg in sections
> Update & re-organize expr helpers

- crowdsec-docs/docs/preview/1-5/intro.md
- crowdsec-docs/docs/preview/backup_guide.mdx
- crowdsec-docs/docs/preview/building.md
- crowdsec-docs/docs/preview/preview_crowdsec_linux.mdx
- crowdsec-docs/docs/preview/preview_crowdsec_windows.md
- crowdsec-docs/docs/preview/rollback.mdx
- crowdsec-docs/sidebars.js
https://pr-353.d1to60jd2gb6y6.amplifyapp.com/docs/next/preview/1-5/intro/
> Preview page

- crowdsec-docs/docs/whitelist/create.md
the documentation doesn't report to create a postoverflow whitelist with FQDN
> doc.create whitelist by FQDN

- crowdsec-docs/docs/notification_plugins/telegram.md
- crowdsec-docs/versioned_docs/version-v1.4.0/notification_plugins/telegram.md
This example put the shodan as inline_keyboard and add a link to crowdsec cti as well
> A more advanced telegram example

- crowdsec-docs/docs/getting_started/getting_started_on_windows.md
- crowdsec-docs/docs/getting_started/install.mdx
- crowdsec-docs/docs/getting_started/install_freebsd.md
- crowdsec-docs/docs/user_guides/building.md
- fix #239 
- fix #97 
- remove deprecated windows warning
> Minor changes

- crowdsec-docs/docs/data_sources/file.md
Add some documentation on https://github.com/crowdsecurity/crowdsec/issues/2223
> Add poll_without_inotify documentation and about the defaults change

- crowdsec-docs/docs/bouncers/cloudflare.mdx
We are getting more and more reports of CF rate limits. Adding a clearer warning about free accounts rate limits
> Add warning at top for free accounts

- crowdsec-docs/docs/scenarios/format.md
update conditional bucket doc according https://github.com/crowdsecurity/crowdsec/pull/2412
> update conditional bucket doc

- crowdsec-docs/docs/bouncers/custom.mdx
- crowdsec-docs/versioned_docs/version-v1.0/bouncers/custom.mdx
- crowdsec-docs/versioned_docs/version-v1.1/bouncers/custom.mdx
- crowdsec-docs/versioned_docs/version-v1.2.2/bouncers/custom.mdx
- crowdsec-docs/versioned_docs/version-v1.2/bouncers/custom.mdx
- crowdsec-docs/versioned_docs/version-v1.3.0/bouncers/custom.mdx
- crowdsec-docs/versioned_docs/version-v1.3.4/bouncers/custom.mdx
- crowdsec-docs/versioned_docs/version-v1.4.0/bouncers/custom.mdx
same as https://github.com/crowdsecurity/crowdsec-docs/pull/440 for all branches
> fix repo name for "cs-custom-bouncer"

- crowdsec-docs/docs/getting_started/install_opnsense.md
- crowdsec-docs/versioned_docs/version-v1.4.0/getting_started/install_opnsense.md
same as https://github.com/crowdsecurity/crowdsec-docs/pull/447 for the other branches
> opnsense: full path for memory Settings

- crowdsec-docs/docs/cti_api/taxonomy.md
Adds the crowdsec vpn-proxy label to CTI taxo
> Add vpn proxy to taxonomy

- crowdsec-docs/docs/scenarios/format.md
> leakspeed is for conditional bucket too

- crowdsec-docs/docs/getting_started/versions_matrix.md
> crowdsec matrix update

- crowdsec-docs/docs/getting_started/versions_matrix.md
matrix fixes for openwrt and opensense
> version matrix fixes

- crowdsec-docs/docs/cti_api/getting_started.mdx
- crowdsec-docs/docs/cti_api/taxonomy/behaviors.mdx
- crowdsec-docs/docs/cti_api/taxonomy/classifications.mdx
- crowdsec-docs/docs/cti_api/taxonomy/cti_fields.md
- crowdsec-docs/docs/cti_api/taxonomy/false_positives.mdx
- crowdsec-docs/docs/cti_api/taxonomy/scenarios.mdx
- crowdsec-docs/docs/cti_api/taxonomy/scores.md
- crowdsec-docs/docusaurus.config.js
- Update CTI documentation to add new mitre_techniques and cves in CTI format
- Rename Taxonomy menu names
- Rename "CTI Api" header menu to "CTI  API"
- Update CTI example
> Update CTI documentation

- crowdsec-docs/docs/bouncers/cloudflare-workers.mdx
Fixes suggested by cloudflare team.
> update cf worker bouncer docs

- crowdsec-docs/sidebars.js
Dont use d word, use container and add multiple links :smile:
> [container] Add more links

- crowdsec-docs/docs/observability/dashboard.md
> recommend "sudo env" instead of "sudo -E"

- crowdsec-docs/docs/bouncers/intro.md
- crowdsec-docs/docs/getting_started/install.mdx
- crowdsec-docs/docs/getting_started/intro.md
- crowdsec-docs/docs/getting_started/versions_matrix.md
We repeat ourselves, remove some repeat and improve some sections
> [Install] DRY some docs

- crowdsec-docs/docs/console/intro.md
- crowdsec-docs/docs/cti_api/getting_started.mdx
- crowdsec-docs/docs/getting_started/getting_started.md
- crowdsec-docs/docs/intro.mdx
- crowdsec-docs/docs/observability/prometheus.md
- crowdsec-docs/docs/parsers/create.md
- crowdsec-docs/docs/scenarios/create.md
- crowdsec-docs/docusaurus.config.js
- crowdsec-docs/src/components/AcademyPromo.js
- crowdsec-docs/src/components/RemediationFeatures.js
- crowdsec-docs/versioned_docs/version-v1.5.0/console.md
- crowdsec-docs/versioned_docs/version-v1.5.0/getting_started/getting_started.md
- crowdsec-docs/versioned_docs/version-v1.5.0/observability/prometheus.md
- crowdsec-docs/versioned_docs/version-v1.5.0/parsers/create.md
- crowdsec-docs/versioned_docs/version-v1.5.0/scenarios/create.md
Edit: might not need to fix, only 1080p half screen a little wide
> [academy] Promote academy awareness

- crowdsec-docs/docusaurus.config.js
- crowdsec-docs/plugins/gtag/gtag.js
- crowdsec-docs/plugins/gtag/index.js
- crowdsec-docs/plugins/gtag/theme/cookieconsent.js
- crowdsec-docs/plugins/gtag/theme/styles.module.css
- crowdsec-docs/plugins/gtag/validate.ts
- crowdsec-docs/src/theme/Root.js
Add g-tag analytics and use a basic cookie consent that will not track until user accepts
> Add better analytics with cookie consent

- crowdsec-docs/docs/appsec/quickstart.md
- crowdsec-docs/unversioned/bouncers/nginx.mdx
- crowdsec-docs/unversioned/bouncers/openresty.mdx
Linked to lua issue https://github.com/crowdsecurity/lua-cs-bouncer/issues/60
> Appsec config issue

- crowdsec-docs/unversioned/cti_api/taxonomy/cti_fields.md
> fix range_24_score range

- crowdsec-docs/docs/appsec/installation.md
- crowdsec-docs/docs/appsec/quickstart.md
This changes the appsec howto in the docs to use both generic and vpatch rules
See https://github.com/crowdsecurity/hub/pull/1011
> Add generic rule and use appsec-default as config

- crowdsec-docs/docs/configuration/feature_flags.md
- crowdsec-docs/unversioned/console/decisions/decisions_intro.md
- crowdsec-docs/unversioned/console/decisions/decisions_management.md
- crowdsec-docs/versioned_docs/version-v1.6.0/configuration/feature_flags.md
> enhance: update papi client flags and premium flag

- crowdsec-docs/docs/data_sources/docker.md
Upstream PR: https://github.com/crowdsecurity/crowdsec/pull/2959
> enhance: add use_container_labels documentation

- crowdsec-docs/docs/scenarios/format.md
- crowdsec-docs/versioned_docs/version-v1.6.0/scenarios/format.md
The old link pointed to a no longer existent branch
> Update link in format.md

- crowdsec-docs/docs/appsec/protocol.md
- crowdsec-docs/versioned_docs/version-v1.6.0/appsec/protocol.md
Add documentation about the new header and add a note in `1.6.0` docs
> Appsec user agent header

- crowdsec-docs/unversioned/cti_api/taxonomy/cti_fields.md
Useful update as we're referencing this page to prospect partners like PaloAlto
> Clarified bg noise in cti taxonomy page

- crowdsec-docs/unversioned/troubleshooting/security_engine.mdx
Based on feedback from https://github.com/crowdsecurity/crowdsec/issues/3186
Add example error message and how to fix via bare metal install and container runtimes.
> enhance: Add hash mismatch to faq

- crowdsec-docs/sidebarsUnversioned.js
- crowdsec-docs/unversioned/getting_started/next_steps.md
- crowdsec-docs/unversioned/getting_started/post_installation/whitelists.mdx
Add a whitelist step in getting started so people can whitelist themselves as a general flow on first time install
> enhance: Getting started add whitelist section

- crowdsec-docs/unversioned/console/alerts/background_noise.md
- crowdsec-docs/unversioned/console/security_engines/troubleshooting.md
:recycle: Add the premium icon to the background feature doc page noise
> refactor(alerts): :recycle: Add premium icon to bg noise

- crowdsec-docs/unversioned/bouncers/ingress-nginx.mdx
ref: https://github.com/crowdsecurity/cs-openresty-bouncer/issues/60
> enhance: add warning to ingress nginx about 1.12

- crowdsec-docs/unversioned/bouncers/apache.mdx
> remove bouncer in title

- crowdsec-docs/unversioned/console/alerts/quotas.md
Update community quota documentation regarding the new implementation
> Update community quotas

- crowdsec-docs/unversioned/bouncers/firewall.mdx
many many people are confused about that, this is why I put it on top.
Added tip in intro of firewall bouncer:
https://pr-758.d1to60jd2gb6y6.amplifyapp.com/u/bouncers/firewall#installation
> Add tip to know if you're using nftables and ip tables

- crowdsec-docs/unversioned/bouncers/nginx.mdx
Ppl are confused, lets unconfuse
int install https://pr-759.d1to60jd2gb6y6.amplifyapp.com/u/bouncers/nginx#installation leading to FAQ
> Adding warning about incompatibility wiht ubuntu 22

- crowdsec-docs/unversioned/getting_started/installation/linux.mdx
> enhance: Add about ubuntu pro/esm weights

- crowdsec-docs/unversioned/getting_started/installation/docker.mdx
- crowdsec-docs/unversioned/getting_started/installation/freebsd.mdx
- crowdsec-docs/unversioned/getting_started/installation/kubernetes.mdx
- crowdsec-docs/unversioned/getting_started/installation/linux.mdx
- crowdsec-docs/unversioned/getting_started/installation/macos.mdx
- crowdsec-docs/unversioned/getting_started/prerequisites.mdx
For visual learners use a infographic below the ports
> enhance: Add basic infographic to prereq

- crowdsec-docs/unversioned/cti_api/integration_splunk_siem.md
Mention that API key is editable
> feat(splunk siem): Mention that API key is editable

- crowdsec-docs/unversioned/bouncers/ingress-nginx.mdx
- Make `docker.io` registry explicit
- Specify digest value to avoid pull errors
> update example values file for ingress-nginx
